Project/FilmFinder/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, FileField, SelectField
from wtforms.validators import DataRequired, ValidationError, EqualTo
from FilmFinder.models import User


class RegisterForm(FlaskForm):
    name = StringField(
        label='nick name',
        validators=[
            DataRequired('please input nick name!')
        ],
        description='nick name',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "please input nick name!",
            'required': "required",
            'autofocus': "autofocus"
        }
    )
    first_name = StringField(
        label='first name',
        validators=[
            DataRequired('please input first name!'),
        ],
        description='first name',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "please input first name!",
            'required': "required",
            'autofocus': "autofocus"
        }
    )
    second_name = StringField(
        label='second name',
        validators=[
            DataRequired('please input second name!'),
        ],
        description='second name',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "please input second name!",
            'required': "required",
            'autofocus': "autofocus"
        }
    )

    email = StringField(
        label='email',
        validators=[
            DataRequired('please input email!'),
        ],
        description='email',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "please input email",
            'required': "required",
            'autofocus': "autofocus"
        }
    )
    phone = StringField(
        label='phone',
        validators=[
            DataRequired('please input phone!'),
        ],
        description='phone',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "please input phone!",
            'required': "required",
            'autofocus': "autofocus"
        }
    )
    password = PasswordField(
        label='password',
        validators=[
            DataRequired('please input password!')
        ],
        description='password',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "please input password!",
            'required': "required"
        }
    )
    repassword = PasswordField(
        label='repassword',
        validators=[
            DataRequired('please input repassword!'),
            EqualTo('password', message='password is not match')
        ],
        description='repassword',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "please input repassword!",
            'required': "required"
        }
    )
    submit = SubmitField(
        label='submit',
        render_kw={
            'class': "btn btn-lg btn-success btn-block"
        }
    )

    def validate_name(self, field):
        name = field.data
        num = User.query.filter_by(name=name).count()
        if num == 1:
            raise ValidationError('nick name exists already')

    def validate_email(self, field):
        email = field.data
        num = User.query.filter_by(email=email).count()
        if num == 1:
            raise ValidationError('email exists already')

    def validate_phone(self, field):
        phone = field.data
        num = User.query.filter_by(phone=phone).count()
        if num == 1:
            raise ValidationError('phone exists already')


class LoginFrom(FlaskForm):
    name = StringField(
        label='name',
        validators=[
            DataRequired('please input name!')
        ],

        render_kw={
            'class': "form-control input-lg",
            'placeholder': "please input name!",
            'required': "required"
        }
    )

    password = PasswordField(
        label='password',
        validators=[
            DataRequired('please input password！')
        ],
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "please input password！",
            'required': "required",
            'autofocus': 'autofocus'
        }
    )
    submit = SubmitField(
        label='login',
        render_kw={
            'class': "btn btn-lg btn-success btn-block"
        }
    )

    def validate_name(self, field):
        account = field.data
        num = User.query.filter_by(name=account).count()
        if num == 0:
            raise ValidationError('account is not existed')


class UserDetailForm(FlaskForm):
    name = StringField(
        label='nick name',
        validators=[
            DataRequired('please input nick name!')
        ],
        description='nick name',
        render_kw={
            'class': "form-control",
            'placeholder': "please input nick name!",
            'required': "required",
            'autofocus': "autofocus"
        }
    )
    email = StringField(
        label='email',
        validators=[
            DataRequired('please input email!'),
        ],
        description='email',
        render_kw={
            'class': "form-control",
            'placeholder': "please input email!",
            'required': "required",
            'autofocus': "autofocus"
        }
    )
    phone = StringField(
        label='phone',
        validators=[
            DataRequired('please input phone!'),
        ],
        description='phone',
        render_kw={
            'class': "form-control",
            'placeholder': "please input phone!",
            'required': "required",
            'autofocus': "autofocus"
        }
    )
    face = FileField(
        label='face',
        validators=[
            DataRequired('please upload face!')
        ],
        description='face',
    )
    submit = SubmitField(
        label='save',
        render_kw={
            'class': "btn btn-success"
        }
    )


class CommentForm(FlaskForm):
    content = TextAreaField(
        label='content',
        validators=[
            DataRequired('please input content!')
        ],
        description='content',
        render_kw={
            # 'id': "input_content"
            'class': "form-control",
            'rows': "5"
        }
    )
    star = SelectField(
        label='star',
        validators=[
            DataRequired('please select star！')
        ],
        description='star',
        coerce=int,
        choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')],
        render_kw={
            'class': "form-control"
        }
    )
    submit = SubmitField(
        label='submit',
        render_kw={
            "class": "btn btn-success",
            "id": "btn-sub"
        }
    )

Project/FilmFinder/home/__init__.py
# define blueprint of home function
from flask import Blueprint
home = Blueprint("home", __name__)

from FilmFinder.home import views

Project/FilmFinder/home/views.py
from sqlalchemy.sql import func
from . import home
from flask import render_template, redirect, url_for, flash, session, request, g
from .forms import RegisterForm, LoginFrom, UserDetailForm, CommentForm
from FilmFinder.models import User, UserLog, Film, WishList, Comment, Genre, BlackList, GenreTag, Director, Cast, Direct
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
import os
from FilmFinder import db, app
import uuid
from functools import wraps


def user_login_require(func):
    @wraps(func)
    def decorated_function(*args, **kwargs):
        if session.get('login_user', None) is None:
            return redirect(url_for('home.login', next=request.url))
        return func(*args, **kwargs)

    return decorated_function


@home.route("/")
def index():
    login_user = session.get('login_user')
    login_user_id = session.get('login_user_id')
    user = {
        'login_user': login_user,
        'login_user_id': login_user_id
    }
    return render_template("home/index.html", user=user)


@home.route("/<int:page>/")
def index2(page):
    if not page:
        page = 1
    all_tag = Genre.query.all()
    star_list = [(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')]
    all_star = map(lambda x: {'num': x[0], 'info': x[1]}, star_list)
    import time
    now_year = time.localtime()[0]
    year_range = [year for year in range(int(now_year) - 1, int(now_year) - 5, -1)]
    page_movies = Film.query
    selected = dict()
    genre_id = request.args.get('genre_id', 0)
    if int(genre_id) != 0:
        page_movies = page_movies.filter_by(tag_id=genre_id)
    selected['genre_id'] = genre_id

    star_num = request.args.get('star_num', 0)
    if int(star_num) != 0:
        page_movies = page_movies.filter_by(star=star_num)
    selected['star_num'] = int(star_num)

    time_year = request.args.get('time_year', 1)
    from sqlalchemy import extract, exists, between
    if int(time_year) == 0:
        page_movies = page_movies
    elif int(time_year) == 1:
        page_movies = page_movies
    else:
        page_movies = page_movies.filter(extract('year', Film.release_time) == time_year)
    selected['time_year'] = time_year

    play_num = request.args.get('play_num', 1)
    if int(play_num) == 1:
        page_movies = page_movies.order_by(
            Film.play_num.desc()
        )
    else:
        page_movies = page_movies.order_by(Film.play_num.asc())
    selected['play_num'] = play_num

    comment_num = request.args.get('comment_num', 1)  # 1为从高到低，0为从低到好
    if int(comment_num) == 1:
        page_movies = page_movies.order_by(
            Film.comment_num.desc()
        )
    else:
        page_movies = page_movies.order_by(Film.comment_num.asc())
    selected['comment_num'] = comment_num

    page_movies = page_movies.paginate(page=page, per_page=12)
    return render_template('home/index.html',
                           all_tag=all_tag,
                           all_star=all_star,
                           now_year=now_year,
                           year_range=year_range,
                           selected=selected,
                           page_movies=page_movies)


@home.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginFrom()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data['name']).first()
        if not user.check_password(data['password']):
            flash('password error', category='err')
            return redirect(url_for('home.login'))
        session['login_user'] = user.name
        session['login_user_id'] = user.id
        userlog = UserLog(
            user_id=user.id,
            ip=request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(url_for('home.user'))
    return render_template('home/login.html', form=form)


@home.route('/logout/')
def logout():
    session.pop('login_user', None)
    session.pop('login_user_id', None)
    return redirect(url_for('home.login'))


@home.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data['name'],
            first_name=data['first_name'],
            second_name=data['second_name'],
            password=generate_password_hash(data['password']),
            email=data['email'],
            phone=data['phone'],
        )
        db.session.add(user)
        db.session.commit()
        flash('register successful', category='ok')
        return redirect(url_for('home.login'))
    return render_template('home/register.html', form=form)


@home.route('/user/', methods=['GET', 'POST'])
@user_login_require
def user():
    login_user = User.query.get_or_404(int(session['login_user_id']))
    form = UserDetailForm(
        name=login_user.name,
        email=login_user.email,
        phone=login_user.phone,
    )
    form.face.validators = []
    form.face.render_kw = {'required': False}
    if form.validate_on_submit():
        data = form.data
        face_save_path = app.config['USER_IMAGE']
        if not os.path.exists(face_save_path):
            os.makedirs(face_save_path)
            import stat
            os.chmod(face_save_path, stat.S_IRWXU)

        if form.face.data:
            if login_user.face and os.path.exists(os.path.join(face_save_path, login_user.face)):
                os.remove(os.path.join(face_save_path, login_user.face))

            file_face = secure_filename(form.face.data.filename)
            from ..admin.views import change_filename
            login_user.face = change_filename(file_face)
            form.face.data.save(face_save_path + login_user.face)

        if login_user.name != data['name'] and User.query.filter_by(name=data['name']).count() == 1:
            flash('nick name exists', 'err')
            return redirect(url_for('home.user'))
        login_user.name = data['name']

        if login_user.email != data['email'] and User.query.filter_by(email=data['email']).count() == 1:
            flash('email exists', 'err')
            return redirect(url_for('home.user'))
        login_user.email = data['email']

        if login_user.phone != data['phone'] and User.query.filter_by(phone=data['phone']).count() == 1:
            flash('phone exists', 'err')
            return redirect(url_for('home.user'))
        login_user.phone = data['phone']

        db.session.commit()
        flash('modify successfully', 'ok')
        return redirect(url_for('home.user'))
    return render_template('home/user.html', form=form, login_user=login_user)


@home.route('/comments/<int:page>/')
@user_login_require
def comments(page):
    if not page:
        page = 1
    page_comments = Comment.query.filter_by(
        user_id=int(session['login_user_id'])
    ).order_by(
        Comment.create_time.desc()
    ).paginate(page=page, per_page=10)
    return render_template('home/comments.html', page_comments=page_comments)


@home.route('/wishlist/<int:page>/')
@user_login_require
def wishlist(page):
    if not page:
        page = 1

    wishlists = WishList.query.filter_by(
        user_id=int(session['login_user_id'])
    ).all()
    wishs = []
    for wish in wishlists:
        wishs.append(wish.film_id)
    page_wishlists = Film.query.join(WishList).filter(
        Film.id.in_(wishs)
    ).paginate(page=page, per_page=10)
    return render_template('home/wishlist.html', page_wishlists=page_wishlists)


@home.route('/wishlist/watch/<int:user_id>/<int:page>')
def watch_wishlist(user_id=None, page=None):
    print(user_id)
    if not page:
        page = 1
    wishlists = WishList.query.filter(WishList.user_id == user_id).all()
    wishs = []
    for wish in wishlists:
        wishs.append(wish.film_id)

    page_wishlists = Film.query.join(WishList).filter(
        Film.id.in_(wishs)
    ).paginate(page=page, per_page=10)
    return render_template('home/watch_wishlist.html', page_wishlists=page_wishlists, user_id=user_id, page=page)


@home.route("/wishlist/delete/<int:delete_id>")
@user_login_require
def wishlist_delete(delete_id=None):
    user_id = session['login_user_id']
    wishlist = WishList.query.filter(WishList.film_id == delete_id, WishList.user_id == int(user_id)).first_or_404()
    db.session.delete(wishlist)
    db.session.commit()
    return redirect(url_for('home.wishlist', page=1))


@home.route("/comments/delete/<int:delete_id>")
@user_login_require
def comments_delete(delete_id=None):
    user_id = session['login_user_id']
    comment = Comment.query.filter(Comment.id == delete_id, Comment.user_id == user_id).first_or_404()
    film = Film.query.filter(Film.id == comment.film_id).first_or_404()
    film.comment_num = film.comment_num - 1;
    db.session.delete(comment)
    db.session.commit()
    flash('delete success！', category='ok')
    return redirect(url_for('home.comments', page=1))


@home.route('/blacklist/<int:page>/')
@user_login_require
def blacklist(page):
    if not page:
        page = 1
    blacklists = BlackList.query.filter_by(
        user_id=int(session['login_user_id'])
    ).all()
    banners = []
    for black in blacklists:
        banners.append(black.banner_id)
    page_blacklists = User.query.filter(
        User.id.in_(banners)
    ).paginate(page=page, per_page=10)
    print(page_blacklists)
    return render_template('home/blacklist.html', page_blacklists=page_blacklists)


@home.route('/search/<int:page>')
def search(page=None):
    if page == None:
        page = 1
    keyword = request.args.get('keyword')
    data_type = request.args.get('type')
    search_films = Film.query.filter(
        Film.name.ilike("%" + keyword + "%"),
    ).order_by(
        Film.star.desc(),
        Film.name.asc()
    ).paginate(page=page, per_page=10)
    search_count = Film.query.filter(Film.name.ilike("%" + keyword + "%")).count()
    print(search_count)

Project/FilmFinder/templates/home/alert_info.html
{% with msgs = get_flashed_messages(category_filter=['ok']) %}
    {% if msgs %}
        {% for msg in msgs %}
            <p>{{ msg }}</p>
        {% endfor %}
    {% endif %}
{% endwith %}
{% with msgs = get_flashed_messages(category_filter=['err']) %}
    {% if msgs %}
        {% for msg in msgs %}
            <p>{{ msg }}</p>
        {% endfor %}
    {% endif %}
{% endwith %}

Project/FilmFinder/templates/home/base.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>FilmFinder</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-film.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>

    {% block css %}{% endblock %}

</head>

<body>
<!--nav-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index', page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:30px;">&nbsp;
            </a>
        </div>

        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="Please input keyword！" id="keyword" value="{{ keyword }}"
                           onkeydown="if(event.keyCode===13)return false;" >

                    <span class="input-group-btn">
                       <select id="select_type" class="form-control">
                          <option>name</option>
                          <option>description</option>
                          <option>genre</option>
                           <option>director</option>
                       </select>
                        <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;Search</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index', page=1) }}"><span class="glyphicon glyphicon-film"></span>&nbsp;Film</a>
                </li>

                 {% if session['login_user_id'] %}
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;Logout</a>
                </li>
                 {% else %}
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;Login</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;Register</a>
                </li>
                {% endif %}


                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;User</a>
                </li>
            </ul>
        </div>


    </div>
</nav>

{% block container %}
    <div class="container" style="margin-top:76px">
        {% block content %}{% endblock content %}
    </div>
{% endblock container %}

<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2020&nbsp;FilmFinder&nbsp;All Right Reserved BY chongchongchong
                </p>
            </div>
        </div>
    </div>
</footer>

<script src="{{ url_for('static', filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });
</script>

<script>
    $(document).ready(function () {
        $("#do_search").click(function () {
            let keyword = $('#keyword').val();
            let type = $('#select_type option:checked').val();
            location.href = "{{ url_for('home.search',page=1) }}?keyword=" + keyword+"&type="+type;
        });
    })
</script>

{% block js %}{% endblock %}
</body>
</html>

Project/FilmFinder/templates/home/comments.html
{% extends 'home/base.html' %}

{% block css %}
    <style>
        .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {
            padding-right: 3px;
            padding-left: 3px;
        }
    </style>
{% endblock %}

{% block content %}
    {% include 'home/usermenu.html' %}
    <div class="col-md-9">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;Comments</h3>
            </div>
            <div class="panel-body">
                <ul class="commentList">
                    {% for comment in page_comments.items %}
                        <li class="item cl">
                            <a >
                                <i class="avatar size-L radius">
                                    {% if  comment.user.face  %}
                                        <img alt="50x50" src="{{ url_for('static', filename='user/' + comment.user.face) }}" class="img-circle" style="border:1px solid #abcdef; width: 50px">
                                    {% endif %}
                                </i>
                            </a>
                            <div class="comment-main">
                                <header class="comment-header">
                                    <div class="comment-meta">
                                        <a class="comment-author" href="{{ url_for('home.user') }}">{{ comment.user.name }}</a>
                                        comment on
                                        <time title="{{ comment.create_time }}" datetime="{{ comment.create_time }}">{{ comment.create_time }}</time>
                                        <a href="{{url_for('home.comments_delete', delete_id=comment.id)}}" class="label label-primary pull-right"><span class="glyphicon glyphicon-play"></span>Delete</a>
                                    </div>

                                </header>
                                <div class="comment-body">
                                    <p>{{ comment.content }}！</p>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                {% import 'home/pagination.html' as pg %}
                {{ pg.render_pagination(page_comments, 'home.comments') }}
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            $("#m-3").addClass('active');
        });
    </script>
{% endblock %}

Project/FilmFinder/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<!-- basic -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- mobile metas -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="initial-scale=1, maximum-scale=1">
<!-- site metas -->
<title>FilmFinder</title>
<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content="">

<link rel="stylesheet" href="{{ url_for('static', filename='css/animate.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/icommon.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery-ui.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/meanmenu.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/nice-select.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.mCustomScrollbar.concat.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.mCustomScrollbar.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.theme.default.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.fancybox.min.css') }}" media="screen">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/slick.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='images/fevicon.png') }}" type="image/gif">


</head>
<body>
	<!-- header section start-->
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="logo" href="{{ url_for('home.index') }}"><img src="{{ url_for('static', filename='images/logo.png') }}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            
        </div>
        {% if user.get('login_user_id') %}
            <div class="login_text"><a href="{{ url_for('home.logout') }}">Logout</a></div>
            <div class="login_text"><a href="{{ url_for('home.user') }}">User</a></div>
            {% else %}
            <div class="login_text"><a href="{{ url_for('home.login') }}">Login Here</a></div>
            <div class="login_text"><a href="{{ url_for('home.register') }}">Register</a></div>
        {% endif %} 

    </nav>
	<!-- header section start-->
	<!-- banner section start-->
	<div class="banner_section layout_padding">
		<div class="container">
			<h1 class="best_taital">FilmFinder</h1>
			<div class="box_main_2">
			    <input type="" class="email_bt" placeholder="keyword" name="" id="keyword">
				<button class="subscribe_bt" ><a id="do_search">Search</a></button>
		    </div>
		    <div class="box_main">
		    	<label class="radio-inline there_text">
		    		<input type="radio" name="type" id='type1' value="name" checked>Name
		    	</label>
		    	<label class="radio-inline there_text">
		    		<input type="radio" name="type" id='type2' value="description">Description
		    	</label>
		    	<label class="radio-inline there_text">
		    		<input type="radio" name="type" id='type3' value="genre">Genre
		    	</label>
                <label class="radio-inline there_text">
		    		<input type="radio" name="type" id='type4' value="director">Director
		    	</label>
		    	
		    </div>
		    <p class="there_text" style="font-size: 40px">FilmFinder is a website for review movies</p>
		    <div class="bt_main" >

		    </div>
		</div>
	</div>
	<!-- banner section end-->
	

<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery-3.0.0.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/custom.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugin.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.mCustomScrollbar.concat.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/owl.carousel.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.fancybox.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
      <script>
      $(document).ready(function() {
          $(".fancybox").fancybox({
              openEffect: "none",
              closeEffect: "none"
          });
      })
      </script>
<script>
    $(document).ready(function () {
        $("#do_search").click(function () {
            let keyword = $('#keyword').val();
            let type = $('input:radio:checked').val();
            location.href = "{{ url_for('home.search',page=1) }}?keyword=" + keyword+"&type="+type;
        });
    })

</script>

     
</body>
</html>